services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb_container
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./../data/pgdata:/var/lib/postgresql/data/pgdata
      - ./../data/start.sql:/docker-entrypoint-initdb.d/start.sql #script que sera executado quando o container for executado
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge